// btstack_config.h for sw2d_btstack - Switch 2 BLE HID Host
#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// BTstack features
#define ENABLE_CLASSIC
#define ENABLE_BLE
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_PERIPHERAL
#define ENABLE_GATT_CLIENT
#define ENABLE_GATT_CLIENT_PAIRING
#define ENABLE_HOGP

#define ENABLE_LOG_INFO
#define ENABLE_LOG_ERROR
#define ENABLE_PRINTF_HEXDUMP

// Memory config
#define HCI_ACL_PAYLOAD_SIZE 512
#define MAX_NR_LE_DEVICE_DB_ENTRIES 4
#define MAX_NR_HCI_CONNECTIONS 4
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_GATT_CLIENTS 1

// HCI
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define HCI_INCOMING_PRE_BUFFER_SIZE 4

// Controller
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define HCI_HOST_ACL_PACKET_NUM 10
#define HCI_HOST_ACL_PACKET_LEN 512
#define HCI_HOST_SCO_PACKET_NUM 0
#define HCI_HOST_SCO_PACKET_LEN 0

// NVM (no persistent storage for now)
#define NVM_NONE
#define NVM_NUM_LINK_KEYS 0
#define NVM_NUM_DEVICE_DB_ENTRIES 1

#endif
